title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
domain: encarmine.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://encarmine.github.io"
twitter_username: jekyllrb
github_username:  jekyll
theme: minima
plugins:
  - jekyll-feed
   - vendor/ruby/
